CREATE DATABASE IF NOT EXISTS your_guardian;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    birthdate DATE,
    email VARCHAR(255),
    password VARCHAR(255),
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wallets (
    id BIGINT UNSIGNED,
    user_id BIGINT UNSIGNED ON DELETE CASCADE,
    balance DECIMAL(10, 2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transaction_categories (
    id BIGINT UNSIGNED,
    name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT UNSIGNED,
    wallet_id BIGINT UNSIGNED ON DELETE CASCADE,
    transaction_category_id BIGINT UNSIGNED ON DELETE SET NULL,
    amount DECIMAL(10, 2) DEFAULT 0.00,
    type ENUM('income', 'expense') DEFAULT 'expense',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bills (
    id BIGINT UNSIGNED,
    user_id BIGINT UNSIGNED ON DELETE CASCADE,
    title VARCHAR(255),
    description TEXT,
    amount DECIMAL(10, 2) DEFAULT 0.00,
    due_date DATE,
    status ENUM('pending', 'paid', 'overdue') DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT UNSIGNED,
    user_id BIGINT UNSIGNED ON DELETE CASCADE,
    title VARCHAR(255),
    message VARCHAR(255),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS task_categories (
    id BIGINT UNSIGNED,
    name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT UNSIGNED,
    user_id BIGINT UNSIGNED ON DELETE CASCADE,
    task_category_id BIGINT UNSIGNED ON DELETE SET NULL,
    title VARCHAR(255),
    description TEXT,
    due_date DATE,
    status ENUM('pending', 'completed', 'failed') DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE users
ADD CONSTRAINT PRIMARY KEY (id),
ADD CONSTRAINT uk_users_email UNIQUE KEY (email);

ALTER TABLE wallets
ADD CONSTRAINT PRIMARY KEY (id),
ADD CONSTRAINT uk_wallets_user_id UNIQUE KEY (user_id),
ADD CONSTRAINT fk_wallets_user_id FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE transaction_categories
ADD CONSTRAINT PRIMARY KEY (id);

ALTER TABLE transactions
ADD CONSTRAINT PRIMARY KEY (id),
ADD CONSTRAINT fk_transactions_wallet_id FOREIGN KEY (wallet_id) REFERENCES wallets(id),
ADD CONSTRAINT fk_transactions_transaction_category_id FOREIGN KEY (transaction_category_id) REFERENCES transaction_categories(id);

ALTER TABLE bills
ADD CONSTRAINT PRIMARY KEY (id),
ADD CONSTRAINT fk_bills_user_id FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE notifications
ADD CONSTRAINT PRIMARY KEY (id),
ADD CONSTRAINT fk_notifications_user_id FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE task_categories
ADD CONSTRAINT PRIMARY KEY (id);

ALTER TABLE tasks
ADD CONSTRAINT PRIMARY KEY (id),
ADD CONSTRAINT fk_tasks_user_id FOREIGN KEY (user_id) REFERENCES users(id),
ADD CONSTRAINT fk_tasks_task_category_id FOREIGN KEY (task_category_id) REFERENCES task_categories(id);
